### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by avalanchy** [avalanchy/tvgrid#1]
### v1.0.0

- [x] Be sure the [IMDb dump](https://www.imdb.com/interfaces/) gives you all the data you need.
- [x] Setup the Django project.
- [x] Add models to store IMDb dump. 
- [x] Add Django command that loads IMDb dump.
- [x] Update Django command to reload IMDb dump with no downtime.
- [ ] Add TVSeries model with admin view to populate shows.
- [ ] Add endpoint that lists TVSeries.
- [x] Add endpoint that details TVSeries.
- [x] Setup the Angular project.
- [ ] Add view that lists TVSeries.
- [ ] Add view that details TVSeries.
